### ISSUE TITLE
Unable to run hbud flatpak

### ISSUE THREAD

**Issue by manikandancode** [swanux/hbud#1]
Ubuntu 22.04.1 Wayland

![Screenshot from 2022-09-23 12-42-52](https://user-images.githubusercontent.com/46480489/191909927-065dbf60-ead4-45f4-8df1-4c26ba9d130f.png)

**Comment by swanux** [comment]
I tested the program in a fresh Ubuntu 22.04.1 Wayland setup, and I was not able to reproduce the issue mentioned above.

The problem is related to locale setting using the `locale` Python module (https://docs.python.org/3/library/locale.html).
Probably your current locale setting (returned from `locale.getlocale()` is invalid somehow?
