### ISSUE TITLE
Multiple issues and ideas

### ISSUE THREAD

**Issue by amit9838** [swanux/hbud#2]
Fedora 37,
Gnome - 43.2
Windowing Sys - Wayland

**Comment by swanux** [comment]
Can you please provide the output from `flatpak run io.github.swanux.hbud`?

**Comment by amit9838** [comment]
[amit@fedora ~]$ flatpak run io.github.swanux.hbud
/app/bin
Running in sandboxed mode
/app/share/hbud/hbud/locale/mo ('en_IN', 'UTF-8')
/tmp /home/amit/.var/app/io.github.swanux.hbud/config/hbud.ini
Rank of target plugin: vah264dec ( 267 )
Traceback (most recent call last):
  File "/app/share/hbud/hbud/HBud.py", line 87, in on_activate
    self.hwa_change()
  File "/app/share/hbud/hbud/HBud.py", line 1395, in hwa_change
    target_element.set_rank(target_rank)
AttributeError: 'NoneType' object has no attribute 'set_rank'
[amit@fedora ~]$

**Comment by swanux** [comment]
Thank you kindly! I see what causes the error (missing vah265dec element), and I shall build in some error handling for this. Later today (GMT+1) when I get back home I'll do some tests and get back to you. 

In the meanwhile, can you please run `gst-inspect-1.0 va` on both your system and in the flatpak container? (You can get in there by `flatpak run --command=sh io.github.swanux.hbud`).

**Comment by amit9838** [comment]
Thanks for you generous reply. Here is what you asked for.

[amit@fedora ~]$ flatpak run --command=sh io.github.swanux.hbud
[📦 io.github.swanux.hbud ~]$ gst-inspect-1.0 va
Plugin Details:
  Name                     va
  Description              VA-API codecs plugin
  Filename                 /app/lib/gstreamer-1.0/libgstva.so
  Version                  1.20.5
  License                  LGPL
  Source module            gst-plugins-bad
  Source release date      2022-12-19
  Binary package           GStreamer Bad Plug-ins source release
  Origin URL               Unknown package origin

  vadeinterlace: VA-API Deinterlacer
  vah264dec: VA-API H.264 Decoder
  vampeg2dec: VA-API Mpeg2 Decoder
  vapostproc: VA-API Video Postprocessor

  4 features:
  +-- 4 elements

[📦 io.github.swanux.hbud ~]$

**Comment by swanux** [comment]
Thank you for the answer, and for reporting this issue. The problem is that I didn't account for hardware and drivers with different support for hardware acceleration. It seems that your hardware / driver combo doesn't support for example accelerated h265 decoding. My GPU for example doesn't support VP9.

Can you please provide the model of your GPU? (Just to make sure my theory is right). In the meanwhile, I'll rewrite the program to handle these differences and probably I'll add the option in preferences to see what kind of HW acceleration is supported on one's hardware.

Edit: [more info on this topic](https://blogs.igalia.com/vjaquez/2021/12/08/gstva-in-gstreamer-1-20/)

**Comment by amit9838** [comment]
Actually I don't have enough knowledge about video decoders and HW acc. 
If i got it right what you said. this is it.

```
[amit@fedora ~]$ lspci -k | grep -EA3 'VGA|3D|Display'
00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 0b)
	DeviceName:  Onboard IGD
	Subsystem: Dell Device 05cb
	Kernel driver in use: i915
```

Please correct me if i'm wrong.

**Comment by swanux** [comment]
Yes, it's perfect. Here we can see that you have integrated graphics from your 4th gen Intel CPU (Haswell). As you can see in the last column of the attached table, your hardware doesn't support H265/HEVC decoding. You have nothing to do with it, I'm already working on the fix for HBud (gonna publish soon in 0.4.1.2), just some insight. 

![Screenshot 2023-02-08 at 15-19-06 Intel graphics](https://user-images.githubusercontent.com/44605433/217557787-a98806bc-fc64-4486-a533-9c4ec9cf900b.png)

**Comment by swanux** [comment]
The new release is published, it should be available from the public flathub repo in 3-5 hours as an update.

Let me know if it works as expected.

**Comment by amit9838** [comment]
Great! now it is working fine.
but i encountered a problem in video player.
When I launch the app and choose a video from file picker then it works fine, but when I play a video with `open with`  option then it dosen't play anything (audio player works).

**Comment by swanux** [comment]
Interesting. The problem is related to flatpak permissions (by default, HBud doesn't have permission to read anything outside your Music and Videos folders). However, double clicking on a file, should give read permission to a program through portals - and in my case it works as expected. My main OS is also Fedora 37 with the latest software, but I tested it in a virtual machine as well just to be sure. 

Can you describe exactly your scenario? (which file manager do you use, where's the file, etc so I can try and reproduce the error).

As a workaround, you can grant access to your /home directory with Flatseal easily, you can try that too and let me know if it works.

**Comment by amit9838** [comment]
- I'm using default file manager(nautilus) of fedora.
- The problem is,  when I try to play a video from file manager then it dosen't load the video in the player. But when i browse the file from HBud file picker then it works file.
- Actually it worked when I gave permision of the home folder, on the other hand other video players dosen't necesserly need this permission (read access to home folder).

- This behaviour is not seen in the audio player. 
- I can't find any way to reproduce the error in this scenario.

**Comment by swanux** [comment]
Yeah the whole home folder permission is rather a workaround. I didn't gave this permission on my install / in a fresh install and it worked without it. It's especially interesting that audio works as expected. 

I won't be available in the next 4 days, but after that I'll try and reproduce the issue somehow. If there aren't any new findings, I probably won't be able to do much about it without being able to reproduce the issue.

**Comment by amit9838** [comment]
Ok, In case I find any more issues, i'll definitly report that.
I'm also planing to contribute,  but i think my code-quality and knowledge is not up to the mark.
 
btw thanks for beautiful app.

**Some ideas**
Are you planning to extend features of the player (primerly audio section) like showing songs list, album, artist,  playlist, and fetching songs frrom online resources(like yt-public api) and so on.

**Comment by swanux** [comment]
Okay so just got back. I see, yes of course, a reported bug is a half solved one. 

Well you're welcome. Though, it's far from being stable / ready, and I basically just wrote it for my needs, then decided to share in case anyone is interested. 

Don't worry about code quality. As you can see, mine isn't the best either, to say the least. 

Regarding the ideas, what do you mean by:

- showing songs list
- album, artist, playlist (it already supports these? Or perhaps you mean something different?)
- Fetching from online sources. Like downloading music from there? In that case, there are many specialised programs which do the work much better. I was thinking about implementing something like it, but this program isn't really a music downloader.

**Comment by amit9838** [comment]
Great! :smile: 
Actuallly i was asking whether are you palnnig to add these features?
Because as i can see in current version, app dosen't remembers the directory that was selected,  when it is reopened.
and one more issue that i experinced is that, when i choose a certain directory for music, it dosen't read the audio files from the child directories.

**About online resources**
- I was suggesting that how about if we can search for the songs from online resources like youtube and stream directly.

**Comment by swanux** [comment]
Well, from the features mentioned above I think only the online sources part is missing. I don't know yet if it'd be worth it to add, maybe some time. But first, there are many parts of the program which do need polishing, also some basic functionality (like MPRIS support) is still missing.

> Because as i can see in current version, app doesn't remembers the directory that was selected, when it is reopened.
and one more issue that i experienced is that, when i choose a certain directory for music, it doesn't read the audio files from the child directories.

Remembering the directory is something that might be worth doing. Also, probably making the save playlist option a bit better. For child directories, they're not included on purpose. It's because the program basically treats directories as playlists - and having a playlist inside a playlist is not wanted. But maybe there could be different behaviors for those who don't necessarily only use playlists, but want a simple scan for all approach.

**Comment by amit9838** [comment]
Yes i also missed to mention MPRIS support 😊, 

How about scanning all the files along with children dirs. adding a folder view similar to artist, album view. Which will eventually seperate all the tracks into folders(to say playlist). And may be more features can be added in the future like, favourite list ,or playlist 1,2,3 etc. 

I think these featured nees a lot of work to be done in the UI as well as other parts.

These are just my suggestions regarding the app, people may find a lot of alternatives with above features. If you are making this just for fun then you may ignore these suggestions.

**Comment by swanux** [comment]
Better playlist management, and probably new features with it (like favorite option) are planned. To scan all files however, I have a different approach in mind, one which wouldn't turn the audio section into a file browser.

Yes, it may require some time - days, weeks or months, depending how much time I can spend on this. If everything goes well I'd say a couple of weeks after I start working on them. But probably I'd prioritize MPRIS first.

Yes of course, ideas are appreciated. I certainly do not want to make a full fledged audio and video player and compete with the big ones - I only want something simple yet handy. But the current state is far from what I have in mind, so it's going to change a lot (if you look into the older versions, or HTidal, my other project it was initially based on, you'll see how much it already changed - it's kind of fun to see the "evolution").

Edit: Also, of course feel free to clone / fork and play around with the code as you wish (under the conditions of the GPL-3 license).

**Comment by swanux** [comment]
> When I launch the app and choose a video from file picker then it works fine, but when I play a video with open with option then it dosen't play anything (audio player works).

> Actually it worked when I gave permision of the home folder, on the other hand other video players dosen't necesserly need this permission (read access to home folder).

@amit9838 Quick question. Can you please show an example video player which doesn't need these permissions to work? (I can't seem to find one, but I want to look into it in detail before the quite big 0.4.2 release).

**Comment by amit9838** [comment]
https://user-images.githubusercontent.com/61614402/225085517-a0673049-bbb4-47ff-bab2-8ae234970b5b.mp4

Waiting for the release :smile:
